source "https://rubygems.org"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1"
gem "rack-cors"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :test do
  gem "minitest"
end
